---
- name: Install dehydrated
  ansible.builtin.apt:
    install_recommends: no
    update_cache: yes
    cache_valid_time: 3600
    pkg:
      - dehydrated

- name: Ensure directory for clean_challenge hooks is present
  ansible.builtin.file:
    path: /etc/dehydrated/clean_challenge-hooks
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Install ip.sh config file
  ansible.builtin.copy:
    src: ip.sh
    dest: /etc/dehydrated/conf.d/ip.sh
    owner: root
    group: root
    mode: 0644

- name: Install mail.sh config file
  ansible.builtin.copy:
    src: mail.sh
    dest: /etc/dehydrated/conf.d/mail.sh
    owner: root
    group: root
    mode: 0644

- name: Install hook.sh config file
  ansible.builtin.copy:
    src: hook.sh
    dest: /etc/dehydrated/conf.d/hook.sh
    owner: root
    group: root
    mode: 0644

- name: Install dehydrated-hook.sh script
  ansible.builtin.copy:
    src: dehydrated-hook.sh
    dest: /usr/local/scripts/dehydrated-hook.sh
    owner: root
    group: root
    mode: 0755

- name: Install systemd service file
  ansible.builtin.copy:
    src: dehydrated.service
    dest: /etc/systemd/system/dehydrated.service
    owner: root
    group: root
    mode: 0644

- name: Install systemd timer file
  ansible.builtin.copy:
    src: dehydrated.timer
    dest: /etc/systemd/system/dehydrated.timer
    owner: root
    group: root
    mode: 0644

- name: Enable and start systemd timer
  ansible.builtin.systemd:
    daemon_reload: yes
    name: dehydrated.timer
    state: started
    enabled: yes
    masked: no

- name: Accept CAs terms of service
  shell: /usr/bin/dehydrated --register --accept-terms

- name: Add domains.txt file
  ansible.builtin.template:
    src: domains.txt.j2
    dest: /etc/dehydrated/domains.txt
    owner: root
    group: root
    mode: 0644

- name: Add credentials file for dehydrated-hook.sh script
  ansible.builtin.template:
    src: dehydrated-credentials.sh.j2
    dest: /usr/local/scripts/dehydrated-credentials.sh
    owner: root
    group: root
    mode: 0700
