---
- name: Pass bridged traffic to iptables
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: '1'

- name: Install prerequisite packages
  apt:
    force_apt_get: yes
    install_recommends: no
    name: ['apt-transport-https', 'curl']
    update_cache: yes
    cache_valid_time: 3600

- name: Add Google Cloud APT repository signing key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg

- name: Add Kubernetes APT repository source
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    filename: kubernetes

- name: Install Kubernetes
  apt:
    force_apt_get: yes
    install_recommends: no
    name: ['kubelet', 'kubeadm', 'kubectl']
    update_cache: yes
