---
- name: Install OpenSMTPD
  ansible.builtin.apt:
    install_recommends: no
    update_cache: yes
    cache_valid_time: 3600
    pkg:
      - opensmtpd

- name: Install OpenSMTPD config file
  ansible.builtin.copy:
    src: smtpd.conf
    dest: /etc/smtpd.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart OpenSMTPD

- name: Install aliases table file
  ansible.builtin.copy:
    src: aliases
    dest: /etc/aliases
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart OpenSMTPD

- name: Install secrets table file
  ansible.builtin.template:
    src: secrets.j2
    dest: /var/lib/opensmtpd/secrets
    owner: root
    group: opensmtpd
    mode: 0640
  notify:
    - Restart OpenSMTPD
