---
- name: Install Postfix and ancillaries
  ansible.builtin.apt:
    install_recommends: no
    update_cache: yes
    cache_valid_time: 3600
    pkg:
      - postfix
      - bsd-mailx

- name: Ensure no other MTA is installed
  ansible.builtin.apt:
    state: absent
    purge: yes
    pkg:
      - opensmtpd
      - exim
      - exim4

- name: Install aliases table file
  ansible.builtin.copy:
    src: aliases
    dest: /etc/aliases
    owner: root
    group: root
    mode: 0644
  notify:
    - Regenerate alias database
    - Reload Postfix

- name: Install SASL credentials file
  ansible.builtin.template:
    src: sasl-credentials.j2
    dest: /etc/postfix/sasl-credentials
    owner: root
    group: postfix
    mode: 0640
  notify:
    - Reload Postfix

- name: Install Postfix config file
  ansible.builtin.template:
    src: main.cf.j2
    dest: /etc/postfix/main.cf
    owner: root
    group: root
    mode: 0644
  notify:
    - Reload Postfix
