---
- hosts: all
  vars_files:
    - vars/vault.yml
  roles:
    - resolvconf
    - system
    - getty
    - firewall
    - ssh
    - mta
    - packages
    - users
    - telegraf

- hosts: casilda
  roles:
    - virt

- hosts: corcoran
  vars_files:
    - vars/dehydrated_corcoran.yml
    - vars/apache_corcoran.yml
    - vars/restic_corcoran.yml
  roles:
    - dehydrated
    - apache
    - restic

- hosts: frederic
  vars_files:
    - vars/dehydrated_frederic.yml
    - vars/nginx_frederic.yml
  roles:
    - dehydrated
    - nginx
    - influx

- hosts: hildebrand
  vars_files:
    - vars/knot_hildebrand.yml
    - vars/dehydrated_hildebrand.yml
    - vars/nginx_hildebrand.yml
  roles:
    - knot
    - ddnsd
    - dehydrated
    - nginx

- hosts: blanche
  vars_files:
    - vars/haproxy_blanche.yml
  roles:
    - haproxy
