---
- hosts: all
  vars_files:
    - vars/vault.yml
  roles:
    - system
    - firewall
    - ssh
    - mta
    - packages
    - users
    - telegraf

- hosts: mythic
  roles:
    - resolvconf

- hosts: latham
  roles:
    - resolvconf
    - getty

- hosts: hypervisors
  roles:
    - virt

- hosts: webservers
  roles:
    - dehydrated
    - apache
    - restic

- hosts: influxdbservers
  roles:
    - dehydrated
    - nginx
    - influx

- hosts: authdnsservers
  roles:
    - knot
    - ddnsd
    - dehydrated
    - nginx

- hosts: proxyservers
  roles:
    - haproxy
