---
- hosts: all
  vars_files:
    - vars/vault.yml
  roles:
    - system
    - getty
    - firewall
    - ssh
    - mta
    - packages
    - users
    - telegraf

- hosts: casilda
  roles:
    - virt

- hosts: corcoran
  vars_files:
    - vars/dehydrated_corcoran.yml
    - vars/apache_corcoran.yml
  roles:
    - dehydrated
    - apache
