---
- hosts: all
  vars_files:
    - vars/vault.yml
  roles:
    - system
    - firewall
    - ssh
    - mta
    - packages
    - users
    - telegraf

- hosts: mythic
  roles:
    - resolvconf

- hosts: latham
  roles:
    - resolvconf
    - getty

- hosts: casilda
  roles:
    - virt

- hosts: florian
  roles:
    - dehydrated
    - nginx

- hosts: corcoran
  roles:
    - dehydrated
    - apache
    - restic

- hosts: frederic
  roles:
    - dehydrated
    - nginx
    - influx

- hosts: hildebrand
  roles:
    - knot
    - ddnsd
    - dehydrated
    - nginx

- hosts: blanche
  roles:
    - haproxy
