---
- name: Install prerequisite packages
  ansible.builtin.apt:
    install_recommends: no
    update_cache: yes
    cache_valid_time: 3600
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - wget

- name: Add Docker APT repository signing key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    owner: root
    group: root
    mode: 0444

- name: Add Docker APT repository source
  ansible.builtin.deb822_repository:
    name: docker
    types: deb
    uris: https://download.docker.com/linux/ubuntu
    suites: '{{ ansible_distribution_release }}'
    components: stable
    architectures: amd64
    signed_by: /etc/apt/keyrings/docker.asc

- name: Install Docker
  ansible.builtin.apt:
    install_recommends: no
    update_cache: yes
    cache_valid_time: 3600
    pkg:
      - docker-ce
      - docker-compose-plugin

- name: Ensure Docker service starts at boot
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: yes
    masked: no
