---
- name: Install Apache web server
  ansible.builtin.apt:
    install_recommends: no
    update_cache: yes
    cache_valid_time: 3600
    pkg:
      - apache2

- name: Install SSL options config file
  ansible.builtin.copy:
    src: xjupiter-ssl-options.conf
    dest: /etc/apache2/xjupiter-ssl-options.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - Reload Apache

- name: Install custom config files
  ansible.builtin.copy:
    src: "{{ item }}.conf"
    dest: "/etc/apache2/conf-available/{{ item }}.conf"
    owner: root
    group: root
    mode: 0644
  with_items:
    - allow-override
    - ocsp-stapling
    - proxy-protocol
  notify:
    - Reload Apache

- name: Enable custom config files
  ansible.builtin.file:
    src: "/etc/apache2/conf-available/{{ item }}.conf"
    dest: "/etc/apache2/conf-enabled/{{ item }}.conf"
    state: link
    owner: root
    group: root
    mode: 0644
  with_items:
    - allow-override
    - ocsp-stapling
    - proxy-protocol
  notify:
    - Reload Apache

- name: Remove serve-cgi-bin config
  shell: /bin/rm -f /etc/apache2/conf-enabled/serve-cgi-bin.conf
  notify:
    - Reload Apache

- name: Create virtual host log file directory
  ansible.builtin.file:
    path: /var/log/apache2/{{ item.servername }}
    state: directory
    owner: root
    group: adm
    mode: 0750
  loop: "{{ apache_vhosts }}"

- name: Add virtual host config files
  ansible.builtin.template:
    src: vhost.conf.j2
    dest: /etc/apache2/sites-available/{{ item.servername }}.conf
    owner: root
    group: root
    mode: 0644
  loop: "{{ apache_vhosts }}"
  notify:
    - Reload Apache

- name: Remove pre-existing virtual host symlinks from sites-enabled directory
  shell: /bin/rm -f /etc/apache2/sites-enabled/*

- name: Enable requisite Apache modules
  community.general.apache2_module:
    name: "{{ item }}"
    state: present
  with_items:
    - autoindex
    - cgid
    - headers
    - http2
    - remoteip
    - rewrite
    - ssl
    - status
    - unique_id
  notify:
    - Reload Apache

- name: Create virtual host symlinks in sites-enabled directory
  ansible.builtin.file:
    src: "/etc/apache2/sites-available/{{ item.servername }}.conf"
    dest: "/etc/apache2/sites-enabled/{{ item.servername }}.conf"
    state: link
    owner: root
    group: root
    mode: 0644
  loop: "{{ apache_vhosts }}"
  notify:
    - Reload Apache

- name: Set default virtual host
  ansible.builtin.file:
    src: "/etc/apache2/sites-available/{{ apache_default_vhost }}.conf"
    dest: "/etc/apache2/sites-enabled/000-default.conf"
    state: link
    owner: root
    group: root
    mode: 0644
  notify:
    - Reload Apache

- name: Install dehydrated clean_challenge hook
  ansible.builtin.copy:
    src: reload-apache
    dest: /etc/dehydrated/clean_challenge-hooks/reload-apache
    owner: root
    group: root
    mode: 0755

- name: Install Apache firewall rule
  ansible.builtin.copy:
    src: apache-nft.conf
    dest: /etc/nftables/apache.conf
    owner: root
    group: root
    mode: 0755
  notify: Reload nftables

- name: Install Apache input plugin for telegraf
  ansible.builtin.copy:
    src: apache-telegraf.conf
    dest: /etc/telegraf/telegraf.d/apache.conf
    owner: root
    group: root
    mode: 0644
  notify: Reload telegraf
