---
- name: Install prerequisites for UniFi OS Server
  ansible.builtin.apt:
    install_recommends: no
    update_cache: yes
    pkg:
      - python3-pexpect
      - podman
      - slirp4netns
      - uidmap

- name: Determine if UniFi OS Server needs updating
  ansible.builtin.lineinfile:
    path: /var/lib/uosserver/server.conf
    line: "UOS_SERVER_VERSION=5.0.6"
    create: yes
  check_mode: yes
  register: uos_version

- import_tasks: install.yml
  when: uos_version.changed

- name: Install UniFi OS Server firewall rule
  ansible.builtin.copy:
    src: unifi-nft.conf
    dest: /etc/nftables/unifi.conf
    owner: root
    group: root
    mode: 0755
  notify: Reload nftables

- name: Install UniFi DNS bug fix script
  ansible.builtin.copy:
    src: unifi-dns-fix.sh
    dest: /usr/local/scripts/unifi-dns-fix.sh
    owner: root
    group: root
    mode: 0755

- name: Run UniFi DNS bug fix script after service starts
  ansible.builtin.copy:
    src: dns-fix.conf
    dest: /etc/systemd/system/uosserver.service.d/dns-fix.conf
    owner: root
    group: root
    mode: 0644

- name: Start UniFi OS Server and enable at boot
  ansible.builtin.systemd:
    daemon_reload: yes
    name: uosserver
    enabled: yes
    state: started
    masked: no
