---
- name: Remove default user
  ansible.builtin.user:
    name: ubuntu
    state: absent
    remove: yes

- name: Remove default group
  ansible.builtin.group:
    name: ubuntu
    state: absent

- name: Add chtjonas group
  ansible.builtin.group:
    name: chtjonas
    gid: 1001

- name: Add chtjonas user
  ansible.builtin.user:
    name: chtjonas
    comment: Charlie Jonas
    uid: 1001
    group: chtjonas
    groups: [sudo, adm]
    shell: /bin/bash

- name: Add root SSH authorized_keys
  ansible.posix.authorized_key:
    user: root
    key: https://id.charliejonas.co.uk/secure/authorized_keys

- name: Add chtjonas SSH authorized_keys
  ansible.posix.authorized_key:
    user: chtjonas
    key: https://id.charliejonas.co.uk/secure/authorized_keys

- name: Clone dotfiles repo
  ansible.builtin.git:
    bare: true
    dest: /home/chtjonas/.dotfiles
    repo: 'https://CHTJonas:{{ github_dotfiles_token }}@github.com/CHTJonas/dotfiles.git'
  become: true
  become_user: chtjonas

- name: Setup dotfiles repo
  command: git --git-dir=/home/chtjonas/.dotfiles config status.showUntrackedFiles no
  become: true
  become_user: chtjonas
