---
- name: Install Z shell
  ansible.builtin.apt:
    install_recommends: no
    update_cache: yes
    cache_valid_time: 3600
    pkg:
      - zsh
      - zsh-doc
      - zsh-syntax-highlighting

- name: Remove default user
  ansible.builtin.user:
    name: ubuntu
    state: absent
    remove: yes

- name: Remove default group
  ansible.builtin.group:
    name: ubuntu
    state: absent

- name: Add chtjonas group
  ansible.builtin.group:
    name: chtjonas
    gid: 1001

- name: Add chtjonas user
  ansible.builtin.user:
    name: chtjonas
    comment: Charlie Jonas
    uid: 1001
    group: chtjonas
    groups: [sudo, adm]
    shell: /bin/zsh

- name: Add root SSH authorized_keys
  ansible.posix.authorized_key:
    user: root
    key: https://id.charliejonas.co.uk/secure/authorized_keys

- name: Add chtjonas SSH authorized_keys
  ansible.posix.authorized_key:
    user: chtjonas
    key: https://id.charliejonas.co.uk/secure/authorized_keys

- name: Clone dotfiles repo
  ansible.builtin.git:
    bare: true
    dest: /home/chtjonas/.dotfiles
    repo: 'https://CHTJonas:{{ github_dotfiles_token }}@github.com/CHTJonas/dotfiles.git'
  become: true
  become_user: chtjonas

- name: Setup dotfiles repo
  shell: |
    git --git-dir=/home/chtjonas/.dotfiles config status.showUntrackedFiles no
    git --git-dir=/home/chtjonas/.dotfiles remote set-url --push origin git@github.com:CHTJonas/dotfiles.git
  become: true
  become_user: chtjonas
