---
- name: Update GRUB
  command:
    cmd: /usr/sbin/update-grub

- name: Restart unattended-upgrades
  ansible.builtin.systemd:
    state: restarted
    name: unattended-upgrades

- name: Restart systemd journald
  ansible.builtin.systemd:
    state: restarted
    name: systemd-journald

- name: Reload kernel parameters
  command:
    cmd: /usr/sbin/sysctl --system
