---
- name: Install prerequisite packages
  apt:
    force_apt_get: yes
    install_recommends: no
    name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg2', 'software-properties-common']
    update_cache: yes
    cache_valid_time: 3600

- name: Add Docker APT repository signing key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Add Docker APT repository source
  apt_repository:
    repo: deb https://download.docker.com/linux/raspbian buster stable
    filename: docker

- name: Install Docker
  apt:
    force_apt_get: yes
    install_recommends: no
    name: "docker-ce"
    update_cache: yes
