# This file is managed by Ansible

# Copy Fail (CVE-2026-31431)
install algif_aead /bin/false

# Dirty Frag (CVE-2026-43284)
# Fragnesia (CVE-2026-46300)
install esp4 /bin/false
install esp6 /bin/false
install rxrpc /bin/false

# PinTheft
install rds /bin/false
install rds_tcp /bin/false

# Stuff that has no place in modern networks
install appletalk /bin/false
install ax25 /bin/false
install batman_adv /bin/false
install clip /bin/false
install ieee802154 /bin/false
install lapb /bin/false
install phonet /bin/false
install rose /bin/false
