#!/usr/sbin/nft -f
# This file is managed by Ansible

table inet filter {
	chain input {
		udp dport 3478 accept # STUN
		tcp dport 5005 accept # RTP
		udp dport 5514 accept # Remote syslog capture
		tcp dport 5671 accept # AQMPS
		tcp dport 6789 accept # Speed test
		tcp dport 8080 accept # Device/controller comms
		tcp dport 9543 accept # Identity Hub
		# udp dport 10001 accept # AP discovery/adoption
		udp dport 10003 accept # AP discovery/adoption
		tcp dport 11084 accept # Site Supervisor
	}
}
