[global]
  checkNewVersion = true
  sendAnonymousUsage = false

[log]
  level = "ERROR"

[serversTransport]
  insecureSkipVerify = true

[providers]
  [providers.file]
    filename = "conf.toml"
  [providers.docker]
    exposedByDefault = false

[entryPoints]
  [entryPoints.http]
    address = ":80"
  [entryPoints.https]
    address = ":443"

[certificatesResolvers.xjupiter.acme]
  email = "admin@xjupiter.net"
  storage = "acme.json"
  [certificatesResolvers.xjupiter.acme.tlschallenge]
