---
- name: Install sysctl file
  ansible.builtin.copy:
    src: xjupiter.conf
    dest: /etc/sysctl.d/xjupiter.conf
    owner: root
    group: root
    mode: 0644

- import_tasks: grub.yml

- name: Set timezone to UTC
  timezone:
    name: Etc/UTC

- name: 'Disable motd-news'
  ansible.builtin.systemd:
    name: 'motd-news'
    enabled: no
    masked: yes
  when: ansible_distribution == 'Ubuntu'

- name: Generate British locales
  community.general.locale_gen:
    name: en_GB.UTF-8
    state: present

- name: Set default system locale
  ansible.builtin.copy:
    src: locale
    dest: /etc/default/locale
    owner: root
    group: root
    mode: 0644

- name: Install unattended-upgrades and apticron
  ansible.builtin.apt:
    install_recommends: no
    update_cache: yes
    cache_valid_time: 3600
    pkg:
      - unattended-upgrades
      - apticron

- name: Configure unattended-upgrades
  copy:
    src: unattended-upgrades
    dest: /etc/apt/apt.conf.d/90xjupiter
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart unattended-upgrades.service

- name: Configure apticron
  copy:
    src: apticron.conf
    dest: /etc/apticron/apticron.conf
    owner: root
    group: root
    mode: 0644
