---
- name: Install sysctl file
  ansible.builtin.copy:
    src: xjupiter.conf
    dest: /etc/sysctl.d/xjupiter.conf
    owner: root
    group: root
    mode: 0644

- name: 'Disable RDRAND on boot'
  ansible.builtin.copy:
    dest: '/etc/default/grub.d/disable-rdrand.cfg'
    content: |
      GRUB_CMDLINE_LINUX="nordrand $GRUB_CMDLINE_LINUX"
    mode: '0644'
  notify:
      - 'Update GRUB'

- name: Set timezone to UTC
  timezone:
    name: Etc/UTC

- name: 'Disable motd-news'
  ansible.builtin.systemd:
    name: 'motd-news'
    enabled: no
    masked: yes
  when: ansible_distribution == 'Ubuntu'

- name: Generate British locales
  community.general.locale_gen:
    name: en_GB.UTF-8
    state: present

- name: Set default system locale
  ansible.builtin.copy:
    src: locale
    dest: /etc/default/locale
    owner: root
    group: root
    mode: 0644
