---
- name: Adjust Raspberry Pi Linux command line
  ansible.builtin.replace:
    path: /boot/firmware/cmdline.txt
    regexp: '^([\w](?!.*\b{{ item }}\b).*)$'
    replace: '\1 {{ item }}'
  with_items:
  - "consoleblank=0"
  - "psi=1"
  - "systemd.ssh_auto=no"
  - "cfg80211.ieee80211_regdom=GB"

- name: Remove pi user sudoers config
  ansible.builtin.file:
    state: absent
    path: /etc/sudoers.d/010_pi-nopasswd

- name: Disable Bluetooth
  ansible.builtin.lineinfile:
    path: /boot/firmware/config.txt
    line: dtoverlay=disable-bt

- name: Disable Wi-Fi
  ansible.builtin.lineinfile:
    path: /boot/firmware/config.txt
    line: dtoverlay=disable-wifi
