---
- name: Install Knot signing key
  ansible.builtin.get_url:
    url: https://deb.knot-dns.cz/apt.gpg
    dest: /etc/apt/keyrings/knot.gpg

- name: Install Knot repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/knot.gpg] https://deb.knot-dns.cz/knot-latest/ {{ ansible_distribution_release }} main"
    filename: knot

- name: Install Knot server and utilities
  ansible.builtin.apt:
    install_recommends: no
    pkg:
      - knot
      - knot-dnsutils

- name: Install knot config file
  ansible.builtin.copy:
    src: knot.conf
    dest: /etc/knot/knot.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart Knot

- name: Enable and start systemd unit
  ansible.builtin.systemd:
    name: knot.service
    state: started
    enabled: yes
    masked: no

- name: Install Knot firewall rule
  ansible.builtin.copy:
    src: knot-nft.conf
    dest: /etc/nftables/knot.conf
    owner: root
    group: root
    mode: 0755
  notify: Reload nftables

- name: Install DNS maintenance scripts
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /usr/local/scripts/
    owner: root
    group: root
    mode: 0755
  with_items:
    - update-latham-ddns
    - update-old-vic-ddns

- name: Install systemd service file
  ansible.builtin.copy:
    src: dns-maint.service
    dest: /etc/systemd/system/dns-maint.service
    owner: root
    group: root
    mode: 0644

- name: Install systemd timer file
  ansible.builtin.copy:
    src: dns-maint.timer
    dest: /etc/systemd/system/dns-maint.timer
    owner: root
    group: root
    mode: 0644

- name: Enable and start systemd timer
  ansible.builtin.systemd:
    daemon_reload: yes
    name: dns-maint.timer
    state: started
    enabled: yes
    masked: no
