---
- name: Stop any pre-existing Docker containers
  ansible.builtin.shell: "test -f /srv/docker-compose.yml && cd /srv && docker compose down || true"

- name: Set timezone to UTC
  ansible.builtin.timezone:
    name: Etc/UTC

- name: Install Docker Compose file
  ansible.builtin.copy:
    src: docker-compose.yml
    dest: /srv/docker-compose.yml
    owner: root
    group: root
    mode: 0644

- name: Install Traefik configuration files
  ansible.builtin.copy:
    src: traefik
    dest: /opt
    owner: root
    group: root
    mode: 0600

- name: Touch ACME challenge configuration file
  ansible.builtin.file:
    path: /opt/traefik/acme.json
    state: touch
    owner: root
    group: root
    mode: 0400

- name: Start all Docker containers
  ansible.builtin.shell: "cd /srv && docker compose up -d"
