---
- name: Remove some package bloat
  ansible.builtin.apt:
    state: absent
    purge: yes
    pkg:
      - popularity-contest
      - pollinate
      - sosreport
      - whoopsie
      - landscape-common
      - pollen
      - apport
      - debian-faq
      - laptop-detect
