---
- name: Remove some package bloat
  ansible.builtin.apt:
    state: absent
    autoremove: yes
    purge: yes
    pkg:
      - apport
      - avahi-daemon
      - bluez
      - bluez-firmware
      - debian-faq
      - landscape-common
      - laptop-detect
      - os-prober
      - pollen
      - pollinate
      - popularity-contest
      - rpicam-apps-core
      - sosreport
      - whoopsie
